/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Building {
  house: number;
  id: Generated<string>;
  name: string;
  other: string | null;
  property_id: string | null;
  street: string;
}

export interface Property {
  accountant: string | null;
  id: Generated<string>;
  manager: string | null;
  name: string;
  type: string;
  url: string;
}

export interface Unit {
  building_id: string | null;
  entrance: string;
  floor: number;
  id: Generated<string>;
  number: number;
  ownership_share: string;
  rooms: number;
  size: number;
  type: string;
  year: number;
}

export interface DB {
  building: Building;
  property: Property;
  unit: Unit;
}
